// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guxksxpychuievwwzvmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eGtzeHB5Y2h1aWV2d3d6dm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDU1NzYsImV4cCI6MjA1NzYyMTU3Nn0.hW8uJkvq4PUrs-DyZhVz8Tg_za2IyHxstcA0Q8f9Z50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);